/*
 * shim_direct.cpp
 * Uses standard Windows COM to load Blackmagic drivers.
 * Requires: DeckLinkAPI.h (generated by widl)
 */

// This define tells Windows to actually CREATE the UUIDs in memory
#define INITGUID 
#include <windows.h>
#include <initguid.h> 

// Include your generated header
#include "DeckLinkAPI.h"

#include <iostream>
#include <vector>
#include <atomic>

// Callbacks for Python
typedef void (*PythonVideoCallback)(uint8_t* v_data, size_t v_len);
typedef void (*PythonAudioCallback)(int16_t* a_data, size_t num_samples);

// --- COM Callback Class ---
class DeckLinkCaptureDelegate : public IDeckLinkInputCallback {
public:
    PythonVideoCallback py_video_cb = nullptr;
    PythonAudioCallback py_audio_cb = nullptr;
    std::atomic<ULONG> m_refCount;

    DeckLinkCaptureDelegate() : m_refCount(1) {}

    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID iid, LPVOID *ppv) {
        *ppv = NULL;
        if (IsEqualIID(iid, IID_IUnknown)) *ppv = static_cast<IUnknown*>(this);
        else if (IsEqualIID(iid, IID_IDeckLinkInputCallback)) *ppv = static_cast<IDeckLinkInputCallback*>(this);
        
        if (*ppv) {
            AddRef();
            return S_OK;
        }
        return E_NOINTERFACE;
    }
    ULONG STDMETHODCALLTYPE AddRef(void) { return ++m_refCount; }
    ULONG STDMETHODCALLTYPE Release(void) {
        ULONG newRef = --m_refCount;
        if (newRef == 0) delete this;
        return newRef;
    }

    HRESULT STDMETHODCALLTYPE VideoInputFrameArrived(
        IDeckLinkVideoInputFrame* videoFrame, 
        IDeckLinkAudioInputPacket* audioPacket) {
        
        if (videoFrame && py_video_cb) {
            void* bytes = nullptr;
            videoFrame->GetBytes(&bytes);
            if (bytes) {
                long rowBytes = videoFrame->GetRowBytes();
                long height = videoFrame->GetHeight();
                py_video_cb((uint8_t*)bytes, rowBytes * height);
            }
        }

        if (audioPacket && py_audio_cb) {
            void* bytes = nullptr;
            audioPacket->GetBytes(&bytes);
            long sampleCount = audioPacket->GetSampleFrameCount();
            if (bytes && sampleCount > 0) {
                py_audio_cb((int16_t*)bytes, sampleCount * 2); 
            }
        }
        return S_OK;
    }

    HRESULT STDMETHODCALLTYPE VideoInputFormatChanged(
        BMDVideoInputFormatChangedEvents events, 
        IDeckLinkDisplayMode* mode, 
        BMDDetectedVideoInputFormatFlags flags) {
        return S_OK;
    }
};

// --- State Wrapper ---
struct Wrapper {
    IDeckLink*              deckLink = nullptr;
    IDeckLinkInput*         deckLinkInput = nullptr;
    IDeckLinkConfiguration* deckLinkConfig = nullptr;
    DeckLinkCaptureDelegate* delegate = nullptr;
};

// --- Exports ---
extern "C" {

    void* init_card() {
        // 1. Initialize COM
        HRESULT res = CoInitialize(NULL);
        
        // 2. Load the Driver using Standard COM (CoCreateInstance)
        IDeckLinkIterator* deckLinkIterator = nullptr;
        res = CoCreateInstance(CLSID_CDeckLinkIterator, NULL, CLSCTX_ALL, IID_IDeckLinkIterator, (void**)&deckLinkIterator);

        if (res != S_OK || !deckLinkIterator) {
            std::cerr << "[Shim] Error: Drivers not installed or COM failed." << std::endl;
            return nullptr;
        }

        Wrapper* w = new Wrapper();

        // 3. Get first card
        if (deckLinkIterator->Next(&w->deckLink) != S_OK) {
            std::cerr << "[Shim] No Blackmagic card found." << std::endl;
            deckLinkIterator->Release();
            delete w;
            return nullptr;
        }

        // 4. Get Input Interface
        w->deckLink->QueryInterface(IID_IDeckLinkInput, (void**)&w->deckLinkInput);
        
        // 5. Get Config Interface
        w->deckLink->QueryInterface(IID_IDeckLinkConfiguration, (void**)&w->deckLinkConfig);

        deckLinkIterator->Release();
        return (void*)w;
    }

    void configure_card(void* ptr, int v_input_index, uint32_t ignored) {
        Wrapper* w = (Wrapper*)ptr;
        if (!w || !w->deckLinkConfig) return;

        // Using constants defined in your generated header
        BMDVideoConnection conn = bmdVideoConnectionHDMI;
        if (v_input_index == 1) conn = bmdVideoConnectionComponent;
        else if (v_input_index == 2) conn = bmdVideoConnectionComposite;
        else if (v_input_index == 3) conn = bmdVideoConnectionSVideo;

        w->deckLinkConfig->SetInt(bmdDeckLinkConfigVideoInputConnection, (LONGLONG)conn);
        w->deckLinkConfig->SetInt(bmdDeckLinkConfigAudioInputConnection, (LONGLONG)bmdAudioConnectionEmbedded); 
    }

    void set_audio_callback(void* ptr, PythonAudioCallback cb) {
        Wrapper* w = (Wrapper*)ptr;
        if (w) {
            if (!w->delegate) w->delegate = new DeckLinkCaptureDelegate();
            w->delegate->py_audio_cb = cb;
        }
    }

    int start_capture(void* ptr, PythonVideoCallback video_cb) {
        Wrapper* w = (Wrapper*)ptr;
        if (!w || !w->deckLinkInput) return 0;

        if (!w->delegate) w->delegate = new DeckLinkCaptureDelegate();
        w->delegate->py_video_cb = video_cb;

        w->deckLinkInput->SetCallback(w->delegate);

        // Try 1080i50 first
        HRESULT res = w->deckLinkInput->EnableVideoInput(bmdModeHD1080i50, bmdFormat8BitYUV, bmdVideoInputEnableFormatDetection);
        w->deckLinkInput->EnableAudioInput(bmdAudioSampleRate48kHz, bmdAudioSampleType16bitInteger, 2);

        if (res != S_OK) {
             // Fallback to PAL if 1080i50 fails
             w->deckLinkInput->EnableVideoInput(bmdModePAL, bmdFormat8BitYUV, bmdVideoInputEnableFormatDetection);
        }

        if (w->deckLinkInput->StartStreams() == S_OK) return 1;
        return 0;
    }

    void stop_capture(void* ptr) {
        Wrapper* w = (Wrapper*)ptr;
        if (w) {
            if (w->deckLinkInput) {
                w->deckLinkInput->StopStreams();
                w->deckLinkInput->DisableVideoInput();
                w->deckLinkInput->DisableAudioInput();
                w->deckLinkInput->SetCallback(nullptr);
                w->deckLinkInput->Release();
            }
            if (w->deckLinkConfig) w->deckLinkConfig->Release();
            if (w->deckLink) w->deckLink->Release();
            if (w->delegate) w->delegate->Release();
            delete w;
            CoUninitialize();
        }
    }
}
